### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by aliabbani** [aliabbani/spaceX-group-project#25]
https://github.com/aliabbani/spaceX-group-project/projects/1
We are a team divided between 2 partners:
Student A: Ali Abbani,
Student B: Robert Baiesita

**Comment by EricMbouwe** [comment]
Hi @aliabbani and @ReshyResh, 

# Status: Approved✔️
Excellent job on this project. Keep it up 👏
Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
